### ISSUE TITLE
Error: No data to import

### ISSUE THREAD

**Issue by Th3D0c0** [poly-hammer/BlenderTools#108]
Hello,
i get an error when exporting my skeleton with animations from blender to unreal.
![image](https://github.com/user-attachments/assets/25970456-63ca-4b4b-aaf4-671b75e2d756)

The two Animations have NLA strips to them:
![image](https://github.com/user-attachments/assets/4eba64a7-3271-437d-8725-70fa296b8a7e)

This is the export folder:
![image](https://github.com/user-attachments/assets/30d6baac-1a0b-41b2-9c49-52105aafb2b5)

Scale is applied to everything.
It only sends the skeletal mesh with the skeleton and a material, not the animations.

Versions:
Blender 4.2.4
Unreal 5.5.0
send2ue 2.6.0

**Comment by JoshQuake** [comment]
Hmm interesting. Could you please attach the blend so I can try and see what's going on

**Comment by Th3D0c0** [comment]
[PlayerArms.zip](https://github.com/user-attachments/files/18067970/PlayerArms.zip)

**Comment by JoshQuake** [comment]
Apologies for the delay in response. The issue is you have two armature modifiers being applied to the same mesh. If you remove the small incorrect armature + modifier then it should be good to go.

![image](https://github.com/user-attachments/assets/e14f506d-b298-450c-8ec8-f7274d41c89e)
![image](https://github.com/user-attachments/assets/173e540c-1d87-4ac7-8044-a5a4c1c2c9e1)
![image](https://github.com/user-attachments/assets/70fa7cf3-f7f1-47c2-9b74-ae3dfa382dd0)
![image](https://github.com/user-attachments/assets/c4d333d6-d8f7-4c6a-9015-3e833dd5ce28)

**Comment by Th3D0c0** [comment]
Ok it worked now! Thanks or the response. Also thanks for keeping this plugin alive!

**Comment by JoshQuake** [comment]
You're welcome!
