### ISSUE TITLE
Send to Unreal - Deformed UVs in Unreal with default Import function from Blender

### ISSUE THREAD

**Issue by MoravianLion** [poly-hammer/BlenderTools#22]
* **Addon:** Send to Unreal
* **Steps to Reproduce the Problem:** Pipeline > Export > Settings dialog > Import > Push assets (all default)
* **Error Log:** No errors related to the object nor UVs in general
* **OS:** Windows
* **Addon Version:** Send to Unreal 2.4.5
* **Blender Version:** Blender 4.1 stable
* **Unreal Version:** Unreal 5.4.2

Just installed both UE and this Blender addon today. It's possible I overlooked something, but doubt so, as I looked through all import settings already. I consider this to be a bug.

Left is manual .glb import and on the right is Send to Unreal sample.

![image](https://github.com/poly-hammer/BlenderTools/assets/38085706/f4cfd8d1-87c5-4be6-a7eb-b57082360d38)

**Comment by JoshQuake** [comment]
Hey there, are you able to provide the model so I can take a look?

**Comment by MoravianLion** [comment]
https://drive.google.com/file/d/1xkC5ai9TrOFKQcdp56LBb_BWwdKgcD64/view?usp=drive_link

![image](https://github.com/poly-hammer/BlenderTools/assets/38085706/c59f47bd-0933-4434-acc7-85b72a333062)

**Comment by JoshQuake** [comment]
Thanks! I'll get back to you when I have time to take a look

**Comment by jack-yao91** [comment]
btw github will let you attach .zip files to comments. That is usually the easiest, to zip up the .blend cause send2ue saves your current setting in the scene data, so that way we can open it and run it with the exact settings you used.

**Comment by JoshQuake** [comment]
> btw github will let you attach .zip files to comments. That is usually the easiest, to zip up the .blend cause send2ue saves your current setting in the scene data, so that way we can open it and run it with the exact settings you used.

yes please send the blend. I'm not getting the same issue with my test. Gonna start just requesting blend files from now on.

**Comment by MoravianLion** [comment]
Guys, I'm little confused now. I already sent the blend file. Now I just
made sure the link is viewable to anyone.

https://drive.google.com/file/d/1xkC5ai9TrOFKQcdp56LBb_BWwdKgcD64/view?usp=sharing

I tried to upload rar file, didn't know about zip.

**Comment by JoshQuake** [comment]
apologies for the confusion. I mistakenly assumed your drive link was going to just be the .glb

I'm taking a look to see what could be going on. Thank you for the blend!

**Comment by JoshQuake** [comment]
Okay so looking at your model and comparing to the default from marketplace, it looks like at some point there was a bake accidentally altering the texture files. Since the Unreal materials use grayscale textures and apply a colour to it, I'm guessing to export it tries to bake the material. Since there is a lot of overlapping UVs, it bakes into a mess.

![image](https://github.com/poly-hammer/BlenderTools/assets/3147154/910739f7-1d5a-441b-a43a-488ee1516b35)

As this isn't an issue with Send2UE, I will have to close this. You will need to replicate the unreal material setup in blender or find a different way to export the materials. I'm pretty sure there is a possibly free tool or marketplace plugin out there but I can't remember it off the top of my head.

**Comment by MoravianLion** [comment]
I see. Yes, I noticed that material later when looking more into it. It makes sense.

Thank you for clarifying!
