### ISSUE TITLE
Export Dialog Root Path (Send2UE)

### ISSUE THREAD

**Issue by shufflerror** [poly-hammer/BlenderTools#37]
Hey guys, first of all thank you very much for reviving this great little tool. 

I have got a little suggestion for a cleaner interface.
It would be nice to have a kind of root path field for the Export Settings Dialog. So you don't have to paste the same path in three different fields (Mesh, Animation, Groom), for the UE project paths and export to disk paths. Then there could be an additional field for the subfolders (Animation...)

Cheers

**Comment by JoshQuake** [comment]
Heyo! I like the suggestion, although I think the current setup allows more freedom for the user to put them exactly where they want them regardless of their file structure. They might not want everything under the same root directory. Worth talking about and considering though.

More opinions please!

**Comment by mahreeoocedev01** [comment]
> Heyo! I like the suggestion, although I think the current setup allows more freedom for the user to put them exactly where they want them regardless of their file structure. They might not want everything under the same root directory. Worth talking about and considering though.
> 
> More opinions please!

I was about to make the same argument. A few extra paste operations every now and then is better than a hard limitation.

**Comment by shufflerror** [comment]
Ola, we could have both. This could be achieved with a relativ/absolute path checkbox

**Comment by youthatninja** [comment]
What about : Export to current folder opened in UE? That would solve some other issues

**Comment by jack-yao91** [comment]
I think that there are many ways to achieve the same thing. The big thing that this addon solves is a fully preconfigured pipeline from blender to unreal, so that teams can enforce consitent settings. There are already lots of ways to configure the addon, and I don't think it is creating any hard limitations on a workflow.

The thing I would like to avoid is bloating the addon with more options than it already has.  It kinda becomes and ever increasing matrix of possibilities that could potentially break an existing working feature.

I think the idea of [extensions](https://poly-hammer.github.io/BlenderTools/send-to-unreal/customize/extensions/) is great for stuff like this, where it is fairly easy to write a small script that modifies the addon to your liking.

**Comment by wrstldev** [comment]
Since feedback was asked for, something to consider is some of us have been using this plugin for years and have countless models already set up with the current naming conventions and folder structures. It takes 2 seconds for you guys to type your paths in, which is a drop of water in the ocean compared to the time it takes to actually make the content.

For the rest of us, it takes a lot longer to rename countless models, and the make a huge mess of our project content folders to adapt to these changes. I had to give the previous maintainer a bit of grief for exactly that and him to revert something. I'm several years and upwards of 1000 models deep. You can't just change naming conventions or core functionality on a random Wednesday morning.

**Comment by JoshQuake** [comment]
Yep agreed. Going to close as wont fix. Thank you everyone for your feedback.

**Comment by shufflerror** [comment]
Oh yes I agree with the files already set up issue. Didn't thought about it. 

It was only bugging me on the last project setup, where I had to fill in the paths several hundred times.

Maybe on the next setup I will somehow automate this via script or recorded action.

Thanks for your inputs and suggestions (on a random Wednesday morning :)

**Comment by JoshQuake** [comment]
D: Ouch. You can save out a template and share across projects/computers. I personally have a common preset saved and set in my default blender startup file so it's always exactly how I normally like it.

**Comment by shufflerror** [comment]
Haha, I didn't see this section on my tunneling hustle by setting up. The problem is already solved, but I didn't realized. facepalm
