### ISSUE TITLE
Send2ue Trouble exporting anything other than the blender cube

### ISSUE THREAD

**Issue by frankr2994** [poly-hammer/BlenderTools#78]
I can export the blender cube seemingly fine with default settings. However when trying to export any other object I am getting mesh of random size, materials not finding textures. I'm sure alot of this plays into my lack of blender and unreal knowledge. But I'd appreciate any help. I am trying to assist some others streamline modding into a VR game.  The objects I'm trying to import into unreal are guns that are made up of multiple meshes. They load and color fine into blender.

**Comment by JoshQuake** [comment]
If you'd like to attach your blend I can take a look and tell you what's going on

**Comment by frankr2994** [comment]
https://drive.google.com/file/d/1-bHtVZqQPseA2yGlFj4-Ot2fxFlWc5p-/view

**Comment by frankr2994** [comment]
Sorry didn't mean to close this. I appreciate any help you offer.

**Comment by JoshQuake** [comment]
Hmm okay so there's a couple things going on.

- The armature modifiers are missing for half the objects.
- The few parts that do have the modifier dont have the vertex group to be properly controlled by their respective bone.
- The gun is facing 90 degrees to whats expected of default export settings so you will need to changed the Front Axis in the export settings until it's facing the correct way.
- I would personally merge the parts into one object after setting up the vertex groups on the individual pieces if it's not important to keep them separate. Otherwise Send2UE will create a new skeleton for each part.
- The materials are a bit more than just plugged in textures so Send2UE isn't able to replicate in UE. You will need to manually recreate the material in UE and import the textures yourself unfortunately.

**Comment by frankr2994** [comment]
Ok well I really appreciate you taking a look. For what I need I found that removing the rig and bones from export let me get the meshes over correctly. All the materials get made blank but atleast are moved over and named correctly. I imported all my texture maps separately so I can more or less build the materials without much effort. I will need to keep the parts separate instead of a single object. 

So the only thing that could possibly speed it up more for me is if there was a way for the materials to locate and grab the texture maps I already have sitting in unreal editor.

**Comment by JoshQuake** [comment]
Blender's FBX exporter doesn't seem to be very reliable in seeing the required textures if there are nodes between the sampler and BSDF. Further testing is needed.

There are a couple ways to go about resolving this but it won't be a priority for now. I think it can definitely be improved, though.

For now if you wish you could create a Send2UE extension to do something like crawl the materials for the textures manually pre import, find them in UE, and set the material up post import. Though that's understandably a lot of work for your purposes.
