### ISSUE TITLE
Send2UE: Policy violation warnings

### ISSUE THREAD

**Issue by DanMcLaughlin** [poly-hammer/BlenderTools#82]
### In the description paste in and edit the following:
* **Addon:**Send to Unreal
* **Addon Version:** Send to Unreal 2.4.9
* **Blender Version:** Blender 4.2.1

![image](https://github.com/user-attachments/assets/a90184f6-4d55-4604-8ef5-a8a11d40246f)

**Comment by JoshQuake** [comment]
Thanks! We are aware; it has to do with blenders Extensions platform policies. Send2UE's extensions are loaded in a way that doesn't comply so it requires a rework that also won't break user-made extensions. Progress is being made when time permits but I'm broke af and currently focusing most of my energy more on my game to get it into early access by the end of the year.

I'm still squashing smaller bugs as they come up, but without donations I can't justify committing the time myself to the full Send2UE extensions rework right now since Send2UE works, just doesn't fully comply yet.

**Comment by DanMcLaughlin** [comment]
No worries, thanks for your work @JoshQuake ! This plugin is absolutely critical, so happy the community is keeping it going.

**Comment by virtualfilmer** [comment]
Just wanted to say Josh - you do an amazing job. Don't be rushed by all of us - it's so hard out there for work right now, in CG, film and tv in general. I've never seen the industry like this. So hang in there, and your work is VERY much appreciated!!

**Comment by virtualfilmer** [comment]
Josh I'm sure you know but this error is still happening with SEND TO UNREAL 2.6.0 - the "policy violation with top level module" error. No hurry tho I'm sure its a big one to overcome!

**Comment by JoshQuake** [comment]
Yeeeeep it's the Blender 4.2 Extensions system. Since we're no longer pursuing compliance I will make a patch to remove the manifest toml. That will remove Send2UE from the Extensions menu solving the problem. It will still be found in Add-ons.

**Comment by JoshQuake** [comment]
Thank you for the reminder btw!
